### PR TITLE
Enforcing @peacecorps.gov e-mail

### LINKED ISSUE #43: Peace Corps email verification
## Description
As a PC Hub user 
I need implement Peace Corp login ,
so that I can allow @peacecorps.gov to login using their email

Allowing Peace Corps email users using @peacecorps.gov to login 
## Mocks
signup-1
### Update [Required]
- [ ] @peacecorps.gov users able to login 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours

### PR DESCRIPTION
**Pull request by jericahuang**
### Description
Enforcing users sign up with a @peacecorps.gov e-mail. This form will be used by Peace Corps member registration and there is a plan in #45 for Open Source Community registration with Github OAuth.

Fixes #43

### Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

Tested for invalid e-mails, other e-mail domains, and to that "@peacecorps.gov" is the trailing string. Inputs that don't pass are:
- `asfd`: not an e-mail
- `@peacecorps.gov`: no account name
- `asdf@peacecorps.govn`: "@peacecorps.gov" isn't the trailing string
- `asdf@gmail.com`: not @peacecorps.gov e-mail

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by bethanyr** [comment]
It would be great if you can add a unit test for this functionality - there is currently user model test file - which is empty that you can use: https://github.com/systers/pchub/blob/develop/pc-hub/test/models/user_test.rb

here's a test gude: http://guides.rubyonrails.org/v4.2/testing.html

I have a PR open which cleans up the tests so we can start creating and running tests - you might need to wait until that PR is merged before writing tests, or create another issue to write a test for this PR - which you can work on after we get tests running.

@AngieSky , @Vaibhavi24 - what do you think?

**Comment by Vaibhavi24** [comment]
@bethanyr Yeah, we can first merge the PR submitted by you, its an important one. 
@jericahuang Adding unit tests for the peacecorps email verification is a good idea.

**Comment by bethanyr** [comment]
@AngieSky - it looks like this PR can be merged.

**Comment by jericahuang** [comment]
I should create a new PR with the tests then?

**Pull request merged**
